---
- name: Create dir
  ansible.builtin.file:
    path: "/opt/registry/{{ item }}"
    state: directory
  with_items:
    - auth
    - certs
    - data

- name: Get stats of cert file
  ansible.builtin.stat:
    path: /opt/registry/certs/domain.crt
  register: cert_sym

- name: Get certificate information
  community.crypto.x509_certificate_info:
    path: /opt/registry/certs/domain.crt
  register: cert_info
  when: cert_sym is defined

- name: Delete expired cert and key
  ansible.builtin.file:
    path: "/opt/registry/certs/{{ item }}"
    state: directory
  with_items:
    - domain.crt
    - domain.key
  when: cert_info.expired

- name: Generate Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /opt/registry/certs/domain.crt
    privatekey_path: /etc/ssl/private/domain.key
    provider: selfsigned
  when: cert_sym is not defined or cert_info.expired

- name: Copy generated cert
  ansible.builtin.copy:
    src: /opt/registry/certs/domain.crt
    dest: /etc/pki/ca-trust/source/anchors/
  when: cert_sym is not defined or cert_info.expired

- name: Update CA trust
  ansible.builtin.command: update-ca-trust
  when: cert_sym is not defined or cert_info.expired
